### ISSUE TITLE
Failed import in Node - package.json "main" field not aligned with source

### ISSUE THREAD

**Issue by arimus** [creynders/depres#1]
Module resolution is failing in a Node project I'm trying to use this in, because the package (as installed by NPM) contains "dist/depres.js", but the "main" is set to "src/depres.js" instead. 

Modifying this fixes the the problem and the following works:

```
var depres = require('depres');
```

Note: I am transpiling from TypeScript, but I'm pretty sure the mismatch above isn't correct for the distributed package in any case.

**Comment by creynders** [comment]
Oh, wow, I'm really sorry ... somehow this entirely escaped my attention. I'll update the package.json and cut a new release.

**Comment by creynders** [comment]
In case you still need it: I released it as v0.1.1
